### ISSUE TITLE
Define conventions for repository names and topics in this organization

### ISSUE THREAD

**Issue by hhkaos** [EsriDevEvents/.github#1]
This is my proposal (context at the bottom)

## General rules

| Session type        | Repo title                  | Topics                                              | E.g.                                                                           |
| ------------------- | --------------------------- | --------------------------------------------------- | ------------------------------------------------------------------------------ |
| Technical sessions  | Session to name<sup>1</sup> | `technical-session`, `talk`                         | `arcgis-online-imagery-analysis-using-python`                                  |
| Presummit workshops | Session to name<sup>1</sup> | `presummit-workshops`, `workshop-materials`         | `deep-dive-into-arcgis-arcade-and-automation-with-arcgis-field-maps`           |
| Plenary demos       | Section name<sup>1</sup>    | \[conference\]-\[continent\]\-plenary-\[topic\]-\[year\] | `ds-europe-plenary-web-2022`, `fed-plenary-web-2023`, `uc-usa-plenary-native-2023` |
| User presentations  | Session to name<sup>1</sup> | `presummit-workshops`, `workshop-materials`         | `python-toolboxes-for-developers-and-novice-users`                             |
| Demo theater        | Session to name<sup>1</sup> | `demo-theater`                                      | `an-introduction-to-javascript-for-future-web-developers`                      |
| Speedgeeking        | Edition name                | speedgeeking-\[conference\]-\[continent\]-\[year\]  | `speedgeeking-ds-usa-2023`                                                                             |

> (1)  [Slugify the title of the sessions](https://slugify.online/) using lowercase and separate with dashes 

In addition to the previous topics, add also the followings:

   * `esri` and `arcgis`
   * As many technologies as covered (full list below in the instructions)
   * Developer summits: 
	   * `esri-devsummit`
	   * `ds-` followed by the full year (e.g. `ds-2023`) ??.
	   * `ds-` followed by the continent (e.g. `ds-usa` or `ds-europe`).
   * User conferences:
	   * `esri-user-conference`
	   *  `uc-`followed by the full year (e.g. `uc-2023`)
   * Federal GIS Conference
	   * `esri-federal-gis-conference`
	   * `fed-` followed by the full year (e.g. `fed-2023`)

---

## Draft instructions 

To be included in the [profile/README.md](https://github.com/esridevsummit/.github/tree/main/profile#readme) to help developers find talks:

> These repositories use [GitHub topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to help you find and filter what you are looking for. There are topics available per: 
> * **Session type**: [technical-session](https://github.com/esridevsummit?q=technical-session), [workshop-materials](https://github.com/esridevsummit?q=workshop-materials), [user-presentation](https://github.com/esridevsummit?q=user-presentation), [demo-theater](https://github.com/esridevsummit?q=demo-theater), and [speedgeeking](https://github.com/esridevsummit?q=speedgeeking).
> * **Developer Summit Edition**: 
>    * Per year: [ds-2023](https://github.com/esridevsummit?q=ds-2023), [ds-2022](https://github.com/esridevsummit?q=ds-2022), [ds-2021](https://github.com/esridevsummit?q=ds-2021), ...
>    * And location: [ds-usa](https://github.com/esridevsummit?q=ds-usa) and [ds-europe](https://github.com/esridevsummit?q=ds-europe).
> * **Technology**:  
>    * SDKs, libraries and APIs: [arcgis-js-sdk](https://github.com/esridevsummit?q=arcgis-js-sdk), [arcgis-dotnet-sdk](https://github.com/esridevsummit?q=arcgis-dotnet-sdk), [arcgis-kotlin-sdk](https://github.com/esridevsummit?q=arcgis-kotlin-sdk), [arcgis-swift-sdk](https://github.com/esridevsummit?q=arcgis-swift-sdk), [arcgis-java-sdk](https://github.com/esridevsummit?q=arcgis-java-sdk), [arcgis-qt-sdk](https://github.com/esridevsummit?q=arcgis-qt-sdk), [arcgis-unity-sdk](https://github.com/esridevsummit?q=arcgis-unity-sdk), [arcgis-unreal-sdk](https://github.com/esridevsummit?q=arcgis-unreal-sdk), [arcgis-python-api](https://github.com/esridevsummit?q=arcgis-python-api), [arcgis-rest-api](https://github.com/esridevsummit?q=arcgis-rest-api), [esri-leaflet](https://github.com/esridevsummit?q=esri-leaflet), [esri-maplibre](https://github.com/esridevsummit?q=esri-maplibre), [esri-openlayers](https://github.com/esridevsummit?q=esri-openlayers), ... 
>    * App builders:  [arcgis-appstudio](https://github.com/esridevsummit?q=arcgis-appstudio), [arcgis-experience-builder](https://github.com/esridevsummit?q=arcgis-experience-builder), [arcgis-survey123](https://github.com/esridevsummit?q=arcgis-survey123), [arcgis-web-appbuilder](https://github.com/esridevsummit?q=arcgis-web-appbuilder).
>    * Products: [arcgis-enterprise](https://github.com/esridevsummit?q=arcgis-enterprise), [arcgis-online](https://github.com/esridevsummit?q=arcgis-online), [arcgis-platform](https://github.com/esridevsummit?q=arcgis-platform), [arcgis-pro](https://github.com/esridevsummit?q=arcgis-pro). 
>    * Others: [esri-calcite](https://github.com/esridevsummit?q=esri-calcite), [arcpy](https://github.com/esridevsummit?q=arcpy), [esri-arcade](https://github.com/esridevsummit?q=esri-arcade), ...
> 
> You can use any combination of them and filter per session name. Learn more about [advanced searches](#).

---

## Context

I was talking to Amy, @cyatteau, and @esride-nik about defining a convention to set repo names and ~~tags~~ -> **topics** for this organization. The goal is to make this organization easier to navigate and use while following rules that make sense to contribute to the general GitHub community. 

Following @esride-nik advice, we have created this [organization profile repo](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile).

I'm going to start defining the usual searches I would perform on this organization, from the most frequent searches to the lowest (🔴 High  🟡 Medium ⚪ Low ⚫ Very low). Hopefully, it will help us define the proper system. 

Find a repo with the source code/resources of a specific:
* 🔴 Technical talk I have attended or watched on YouTube (sometimes from a specific year and DevSummit edition)
* 🟡 Demo I have seen on plenary (of a specific DevSummit edition)
* 🟡 Demo theatre/user presentation I have attended 
* ⚪ Speed geeking session I have attended  
* ⚫ Presummit workshop I attended

Filter:
* ⚪ All repositories on a given technology & devsummit edition <-  link from blog articles ([like this](https://www.esri.com/arcgis-blog/products/arcgis-pro-net/developers/arcgis-pro-sdk-sessions-available-from-dev-summit-2022/)), maybe from the developer site in the future
* 🟡 All repositories on a given devsummit edition <- link from [Mediaspace channels](https://mediaspace.esri.com/channel/2022%2BEsri%2BDeveloper%2BSummit/250241443), ...
* ⚫ All repositories on a given format (technical sessions, plenary demos, workshop, ...) <- mainly for audit purposes

> **Notes**: if issues are enabled, please be careful not to use these as forums. Set the repo as the [esri-leaflet](https://github.com/Esri/esri-leaflet-vector/issues/new/choose) to redirect to the right place to ask questions.

**Comment by cyatteau** [comment]
> Set the repo as the [esri-leaflet](https://github.com/Esri/esri-leaflet-vector/issues/new/choose) to redirect to the right place to ask questions.
**What do you mean by this exactly? Do you mean to follow a similar pattern as done in this repo?** 


> Should we define when to archive a repo?
**Yes, at least a general set of guidelines. One reason is if another repo is posted that's very similar and updated, the other should be archived and a link to the newer version should be included in the old one. Another reason is to indicate that the repo is not being maintained to reflect updates and other inevitable future software changes. _NOTE:_ Both of these reasons don't give a timeline of when to archive just a general practice.**

Draft instructions to be included in the [profile/README.md](https://github.com/esridevsummit/.github/tree/main/profile#readme) to help developers find talks:
> Session type: [technical-session](https://github.com/esridevsummit?q=technical-session), [workshop-materials](https://github.com/esridevsummit?q=workshop-materials), [user-presentation](https://github.com/esridevsummit?q=user-presentation), [demo-theatre](https://github.com/esridevsummit?q=demo-theatre), and [speedgeeking](https://github.com/esridevsummit?q=speedgeeking). 
**I like these tags and think they make sense. In relation to technical sessions, I did find this wording "technical workshop" on the Esri Dev Summit [agenda at a glance page](https://www.esri.com/en-us/about/events/devsummit/agenda?date=2023-03-07), though. I doubt it's that big of a deal but thought I would point it out.**
![image](https://user-images.githubusercontent.com/112517097/213448543-bfc7db7c-dbd8-4dc8-9e35-6774c3a31abe.png)


> You can use any combination of them and filter per session name. Learn more about [advanced searches](https://github.com/esridevsummit/.github/issues/1#).
**Did you mean to put a different link when talking about advanced searches? The current link is to this issue.**

**Comment by hhkaos** [comment]
> Set the repo as the [esri-leaflet](https://github.com/Esri/esri-leaflet-vector/issues/new/choose) to redirect to the right place to ask questions.
> **What do you mean by this exactly? Do you mean to follow a similar pattern as done in this repo?**

Yes, I mean making clear how to use issues on these repos. To avoid using issues as Q&A if it makes more sense to forward questions to community.esri.com 

> Should we define when to archive a repo?
> **Yes, at least a general set of guidelines. One reason is if another repo is posted that's very similar and updated, the other should be archived and a link to the newer version should be included in the old one. Another reason is to indicate that the repo is not being maintained to reflect updates and other inevitable future software changes. NOTE: Both of these reasons don't give a timeline of when to archive just a general practice.**

I agree with the second one. So I would say, archive a repository if:
* The source code that is not valid (e.g. old SDK version)
* The technologies are deprecated

In case of repos with very similar I would prefer to reuse the repos a create a new branch. The benefit of doing this is that people that has already starred the repo might receive notification on new pushes.

> I like these tags and think they make sense. In relation to technical sessions, I did find this wording "technical workshop" on the Esri Dev Summit [agenda at a glance page](https://www.esri.com/en-us/about/events/devsummit/agenda?date=2023-03-07), though. I doubt it's that big of a deal but thought I would point it out.

Yes, I suggested "workshop-materials" because [I found +500 repos](https://github.com/topics/workshop-materials) already using it, but both could work

> You can use any combination of them and filter per session name. Learn more about https://github.com/esridevsummit/.github/issues/1#.
**Did you mean to put a different link when talking about advanced searches? The current link is to this issue.**

Yes, I mean adding a link to another markdown file with an extended documentation / tips&tricks to find repositories within the org.

**Comment by hhkaos** [comment]
> **Note**: if you haven't noticed, we have renamed [github.com/EsriDevSummit](https://github.com/EsriDevSummit) to [github.com/EsriDevEvents](https://github.com/EsriDevEvents) because this organization will host repos for other developer events

Before next DevSummit we would like to ground these conventions and adjust the existing repository names to it. 

Any additional feedback to [the current proposal](https://github.com/EsriDevEvents/.github/issues/1#issue-1538559519)? I have scheduled a call to closed this topic [next Thursday (9th February) at 8:30 AM (PST) & 5:30 PM (CET)](https://www.timeanddate.com/worldclock/converter.html?iso=20230209T163000&p1=141&p2=3339&p3=136&p4=37), anyone interested on joining let me know. 

Thanks!

P.S: I have moved [the contributing FAQ](https://github.com/EsriDevEvents/.github/issues/4) to a different discussion.

cc: @Kneeson @cyatteau @esride-nik @ak-kemp @arnofiva @BerndRuprechter @btpschroeder @dmitrykozlov @dstauning @fran2604 @hussein-nasser @JamesMBallard @jf990 @JimBarry @jkieboom @kgonzago @kMcPherson1 @kmorrison-esriuk-com @kyunam @mondal-alex @nCastle1 @nixta @nnoman19 @Qberto @rRuh @rslibed @rwmajor2 @SamueleDecarli @sbiswas96 @schatterjee17 @simonsuo-esri @tlopezcantu @trevorseaton

**Comment by cyatteau** [comment]
@hhkaos - What tag is used for plenary demos? Is it [demo-theater](https://github.com/esridevsummit?q=demo-theatre)?

**Comment by hhkaos** [comment]
Nope, it should follow this pattern: `[conference]-[continent]*-plenary-web-[year]`, so it would be something like:
fed-plenary-web-2023, ds-europe-plenary-web-2022, ds-usa-plenary-web-2022, uc-usa-plenary-native-2023, ...

**Comment by hhkaos** [comment]
does it makes sense? xD I'm thinking maybe just plenary is enough... because it can be combine with the other topics ;)

**Comment by cyatteau** [comment]
> does it makes sense? xD I'm thinking maybe just plenary is enough... because it can be combine with the other topics ;)

It does seem a bit long... I say we stick to just `plenary`.

**Comment by hhkaos** [comment]
[moved to ](https://github.com/EsriDevEvents/contributor-guides/blob/main/conventions.md#conventions-for-repositories)
